components/hospital/feedback/feedback-form.tsx
components/hospital/feedback/feedback.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/quick-order-insert-input.tsx
components/hospital/icu/main/tx-table/tx-table-filter.tsx
components/hospital/icu/main/tx-table/tx-table.tsx
components/ui/scroll-area.tsx

처치표 배경색, 환자목록 sticky, 

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/cell.tsx

refactor: panting(p)인 경우 상향 경고 표시

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/cells-row.tsx
lib/services/patient/patient.ts
lib/supabase/database.types.ts

- 모바일 touch long press
- icu patient info 업데이트 시 환자 번호 누락 수정
어떤 변경 사항이 있나요?

refactor: 모바일 tx 수정 / 환자 번호(hos_patient_id) 업데이트

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-right-buttons/export-dialog/export-dialog-utils.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-right-buttons/export-dialog/export-pdf-button.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-right-buttons/export-dialog/export-png-button.tsx

fix: 날짜별 차트 데이터 페칭 후 내보내기 수정

---

app/hospital/[hos_id]/admin/loading.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/cells-row.tsx

refactor: 시간 선택중인 경우 리얼타임 변경 발생해도 클라이언트 시간상태 유지 + 관리자 로딩 ui height

---

components/common/auto-complete/auto-complete.tsx
components/hospital/icu/footer/realtime-status.tsx
components/hospital/icu/main/search/icu-search-chart.tsx
components/hospital/icu/main/tx-table/tx-table-cell.tsx

refactor: snc improvments

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx

hotfix: longclick 문제 해결

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/cells-row.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx
components/hospital/icu/main/tx-table/tx-table.tsx

처치표 자동 스크롤

---

components/hospital/icu/header/icu-header.tsx
components/hospital/patches/go-to-patch-items-button.tsx
components/hospital/patches/patch-detail.tsx
components/hospital/patches/patch-item.tsx
components/hospital/patches/patch-items.tsx

design: 패치 내역 스타일 수정

---

components/hospital/icu/main/chart/selected-chart/chart-body/chart-memos/memo-group.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/checklist-order/checklist-order-field.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/fluid-order/fluid-order-field.tsx
components/hospital/icu/sidebar/filters/filters.tsx
constants/hospital/icu/chart/order.ts
constants/hospital/icu/fluid/fluid.ts

모바일 소팅 비활성화 + 체크리스트오더 커멘트 상수 + 수액 오더 필드 레이아웃

---

app/hospital/[hos_id]/page.tsx
components/hospital/patches/go-to-patch-items-button.tsx
components/hospital/patches/patch-items.tsx
components/hospital/super/patches/patches-carousel.tsx

chore: 패치노트 스타일링

---

components/hospital/feedback/feedback-form.tsx
components/hospital/feedback/feedback.tsx
components/hospital/icu/header/instruction/instruction-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/cells-row-title.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/fluid-order/fluid-order-field.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/fluid-order/fluid-tool-tip.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/template/confirm-copy-template-order-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/template/template-order-columns.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/template/template-tab-content.tsx
constants/hospital/icu/chart/instruction.ts

오더 다일로그, 단축키 다일로그 lazy loading

---

lib/services/icu/chart/add-icu-chart.ts

fix: prevChartData 페칭 시 최신 순 데이터 하나만 처리

---

components/hospital/home/todo/create-todo-dialog.tsx
components/hospital/home/todo/edit-todo-dialog.tsx
components/hospital/home/todo/single-todo.tsx
components/hospital/home/todo/todo.tsx
lib/services/hospital-home/todo.ts
lib/services/super/patch/patch.ts
lib/store/icu/todo.ts
lib/supabase/database.types.ts

feat: TODO 수정, 삭제 기능 추가

---

components/hospital/home/todo/create-todo-dialog.tsx
components/hospital/home/todo/edit-todo-dialog.tsx
components/hospital/home/todo/single-todo.tsx
components/hospital/home/todo/todo.tsx
lib/services/hospital-home/todo.ts
lib/services/icu/chart/add-icu-chart.ts
lib/services/super/patch/patch.ts
lib/store/icu/todo.ts
lib/supabase/database.types.ts

Develop to Main

---

components/common/new-feature.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/cells-row-title.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/cells-row-titles.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-select-user-step.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-upsert-dialog.tsx
hooks/use-abnormal-vital.tsx
hooks/use-local-storage.tsx

feat: 오더 너비 조절, 새로운 기능 소개

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/cells-row-title.tsx

refactor: 빠른 오더 애니메이션 변경

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-upsert-dialog.tsx

dependancy

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/cells-row-title.tsx

refactor: 오더 너비 transition 효과

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/cells-row-title.tsx

refactor: 오더 애니메이션 all로 수정

---

app/hospital/[hos_id]/icu/[target_date]/tx-table/page.tsx
components/hospital/admin/drug/drug-columns.tsx
components/hospital/common/patient-info.tsx
components/hospital/icu/main/chart/chart.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/cage/cage.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/chart-infos.tsx
components/hospital/icu/main/summary/table/summary-table-row.tsx
components/hospital/icu/main/summary/table/summary-table.tsx
components/hospital/icu/main/tx-table/tx-table.tsx
components/hospital/patients/birth-date-picker.tsx
lib/services/admin/staff/drug-settings.ts
lib/services/icu/chart/update-icu-chart-infos.ts
lib/supabase/database.types.ts
types/adimin/index.ts
types/icu/chart.ts
types/icu/summary.ts
types/icu/tx-table.ts
types/index.ts

- icu_io cage 추가
- birth-date-picker refactoring ( input 비활성화, 특정 연월일 자동 open )
어떤 변경 사항이 있나요?

feat: io 환자의 cage 기능 추가 

---

app/manifest.ts
components/hospital/icu/main/chart/chart-entry.tsx
components/hospital/icu/main/out-and-visit/icu-out-chart/add-out-due-patient-dialog.tsx
components/hospital/icu/main/out-and-visit/visit-chart/add-visit-patient-dialog.tsx
components/hospital/icu/main/summary/table/summary-table-row.tsx
components/hospital/icu/main/tx-table/tx-table-cell.tsx
components/hospital/super/errors/error-log-card.tsx
components/hospital/super/errors/error-logs.tsx
components/hospital/super/feedbacks/feedback-dash-board.tsx

feat: 불필요 `useMemo` 삭제

---

app/hospital/[hos_id]/admin/diet-settings/page.tsx
components/hospital/admin/diet/add-diet-dialog.tsx
components/hospital/admin/diet/diet-columns.tsx
components/hospital/admin/diet/diet-data-table.tsx
components/hospital/admin/diet/diet-schema.ts
components/hospital/admin/diet/diet-species-icon.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/chart-infos.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/rer-der/rer-der-display.tsx
lib/services/admin/diet/diet.ts
types/adimin/index.ts

feat: diet `species` 추가 및 모바일 UI 최적화

---

app/hospital/[hos_id]/admin/diet-settings/page.tsx
components/hospital/admin/diet/add-diet-dialog.tsx
components/hospital/admin/diet/diet-columns.tsx
components/hospital/admin/diet/diet-data-table.tsx
components/hospital/admin/diet/diet-schema.ts
components/hospital/admin/diet/pin-button.tsx
components/hospital/admin/icu-settings/default-orders/default-orders-setting.tsx
components/hospital/admin/icu-settings/icu-settings-tab.tsx
components/hospital/admin/icu-settings/orderer/orderer-setting.tsx
components/hospital/icu/main/chart/add-chart-dialogs/bookmark/add-bookmark-chart-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/fluid-order/fluid-order-field.tsx
lib/services/admin/diet/diet.ts
lib/services/icu/chart/get-diets.ts
lib/supabase/database.types.ts
types/adimin/index.ts
types/icu/chart.ts
types/index.ts

사료 pinning 시스템

---

app/hospital/[hos_id]/admin/diet-settings/page.tsx
components/hospital/admin/diet/add-diet-dialog.tsx
components/hospital/admin/diet/delete-diet-dialog.tsx
components/hospital/admin/diet/diet-columns.tsx
components/hospital/admin/diet/diet-data-table.tsx
components/hospital/admin/diet/pin-button.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/quick-order-insert-input.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/feed-order/feed-order-field.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/fluid-order/fluid-order-field.tsx
lib/services/admin/diet/diet.ts
lib/services/icu/chart/get-diets.ts
lib/supabase/database.types.ts
lib/utils/utils.ts
types/adimin/index.ts
types/icu/chart.ts

feat: diet 기능 완성

---

components/hospital/admin/diet/diet-data-table.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-select-user-step.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-upsert-dialog.tsx
lib/store/icu/tx-mutation.ts

butfix: 오더 커멘트 잔존 오류

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-select-user-step.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-upsert-dialog.tsx

chores: useEffect 의존성 배열

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-form.tsx

rollback: 식이 기능 롤백

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-form.tsx
lib/supabase/database.types.ts

hotfix: 식이 기능 재활성화

---

components/hospital/admin/diet/add-diet-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-select-user-step.tsx
lib/services/admin/diet/diet.ts

build error

---

components/hospital/admin/diet/add-diet-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-form.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-select-user-step.tsx
lib/services/admin/diet/diet.ts
lib/supabase/database.types.ts

chore: rebase develop main

---

app/hospital/[hos_id]/patients/page.tsx
components/hospital/common/patient-info.tsx
components/hospital/icu/main/summary/table/summary-table-row.tsx
components/hospital/super/errors/error-log-card.tsx

style: summary, tx-data, 에러로그 등 ui 수정

---

components/hospital/admin/diet/add-diet-dialog.tsx

update: add-diet-dialog

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/cells-row.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-select-user-step.tsx
lib/services/icu/chart/tx-mutation.ts
lib/store/icu/tx-mutation.ts
lib/supabase/database.types.ts
lib/utils/utils.ts

Feat: TX 몸무게 입력 시 바이탈 업데이트 

---

app/hospital/[hos_id]/icu/[target_date]/chart/[patient_id]/page.tsx
components/hospital/icu/main/chart/add-chart-dialogs/add-chart-dialogs.tsx
components/hospital/icu/main/chart/add-chart-dialogs/add-default-chart-dialog.tsx
components/hospital/icu/main/chart/add-chart-dialogs/bookmark/add-bookmark-chart-dialog.tsx
components/hospital/icu/main/chart/add-chart-dialogs/copy-prev-chart-dialog.tsx
components/hospital/icu/main/chart/add-chart-dialogs/copy-prev-io-chart-dialog.tsx
components/hospital/icu/main/chart/chart-entry.tsx
lib/services/icu/chart/get-icu-chart.ts
types/icu/chart.ts

feat: 신규 입원 시, 최근 마지막 입원 차트 붙여넣기 기능 추가

---

components/hospital/icu/main/summary/table/summary-table-cell.tsx
components/hospital/icu/main/summary/table/summary-table-row.tsx
constants/hospital/icu/chart/colors.ts

design: 종합현황 내 퇴원환자의 미완료 TX 색상 구분

---

app/hospital/[hos_id]/admin/layout.tsx
lib/services/auth/authorization.ts

refactor: admin 확인 과정에서 hos_id 삭제

---

components/hospital/icu/main/chart/selected-chart/chart-body/quick-order-insert-input.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/cells-row-title.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/cells-row-titles.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/mobile/mobile-chart-table.tsx
components/hospital/icu/sidebar/desktop-icu-sidebar.tsx
components/hospital/icu/sidebar/filters/vet-filter.tsx
constants/hospital/icu/chart/order.ts

feat: 기본 체크리스트 `SPO2` 추가, 퀵오더 리팩토링

---

components/hospital/icu/main/tx-table/time-tx-text-copy.tsx
components/hospital/icu/main/tx-table/tx-table-cell.tsx
components/hospital/icu/main/tx-table/tx-table-header.tsx
components/hospital/icu/main/tx-table/tx-table.tsx

hotfix: text 클립보드 저장 불완전 로직 개선

---

components/hospital/icu/footer/icu-footer.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/checklist-order/checklist-order-field.tsx

- 체크리스트 직접 입력 기능 추가 
- icu-footer z-index 20 to 40
어떤 변경 사항이 있나요?

feat: 체크리스트 직접 입력 기능 추가 

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/chart-table-body.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-row-cells.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-row-title.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-rows.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/sorting-order-rows.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx
hooks/use-cell-autofocus.tsx
hooks/use-long-press.tsx
hooks/use-vertical-guideline.tsx
lib/store/icu/icu-order.ts

chart table 리팩토링

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/cell.tsx

hotfix: 처치표에서 이동시 자동포커싱 훅 실행안되고 있었음

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/tx-detail-insert-step.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-schema.ts
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-select-user-step.tsx
components/hospital/icu/main/summary/table/summary-table-cell.tsx
components/hospital/icu/main/summary/table/summary-table-row.tsx
lib/services/icu/analysis/get-analysis-data.ts
lib/services/icu/chart/tx-mutation.ts
lib/store/icu/tx-mutation.ts
lib/supabase/database.types.ts
types/icu/chart.ts
types/icu/summary.ts
types/index.ts

- 수의사 확인이 필요한 처치에 대한 체크박스 기능 추가
어떤 변경 사항이 있나요?

feat: Crucial TX 기능 추가

---

components/hospital/order-table/order-form.tsx

hotfix: 템플릿 내 오더 추가 오류 수정

---

app/hospital/[hos_id]/admin/diet-settings/page.tsx
components/hospital/admin/diet/diet-data-tables.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/cell.tsx

윈도우 오더 시간 설정 오류

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/cell.tsx
hooks/use-long-press.tsx

hotfix: 윈도우 마우스 우클릭 오류

---

components/hospital/admin/icu-settings/icu-settings-card.tsx
components/hospital/admin/icu-settings/vital-ref-range/vital-ref-range-settings.tsx
components/hospital/home/notice/single-notice.tsx
components/hospital/icu/header/register-dialog/search-patient/search-patient-pagination.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/in-and-out-date.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/in-date.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/out-date.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/out-due-date.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/feed-order/feed-order-field.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/fluid-order/fluid-tool-tip.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-time-settings.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/update-patient-dialog.tsx
components/hospital/patches/go-to-patch-items-button.tsx
components/hospital/patches/patch-item.tsx
components/hospital/patches/patch-items.tsx

- 툴팁 side 변경
- vital ref 세팅 input type 변경
- 모바일 UI 리팩토링
어떤 변경 사항이 있나요?

design: 모바일 UI 리팩토링

---

components/common/auto-complete/auto-complete.tsx
components/hospital/admin/staff/name-column.tsx
components/hospital/icu/main/out-and-visit/checklist-input.tsx
components/hospital/icu/main/search/icu-search-chart.tsx
components/hospital/icu/main/tx-table/tx-table-cell.tsx
hooks/use-icu-realtime.tsx
hooks/use-long-press.tsx

design: tx-table 처리 완료한 항목 ring 제거

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx
components/hospital/icu/main/tx-table/tx-table-cell.tsx
components/hospital/icu/main/tx-table/tx-table.tsx
components/hospital/patients/birth-date-picker.tsx
types/icu/tx-table.ts

feat: tx-table 처치표에서 직접 처치 상세 입력 기능

---

app/api/patient/upload/efriends/route.ts
app/api/patient/upload/intovet/route.ts
components/hospital/icu/header/instruction/instruction-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/cpcr-et-tube/cpcr-et-tube.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/in-date.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/vets/vets.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/update-patient-dialog.tsx
components/hospital/patients/upload-patient-area.tsx
constants/hospital/icu/patient/patient.ts
hooks/use-patient-file-upload.tsx
lib/utils/insert-patient.ts

feat: 인투벳 + 이프렌즈 형식의 환자 정보 업로드 기능 추가

---

app/hospital/[hos_id]/icu/[target_date]/layout.tsx
app/hospital/[hos_id]/layout.tsx
components/hospital/header/hospital-header.tsx
components/hospital/icu/footer/icu-footer.tsx
components/hospital/icu/header/icu-header.tsx
components/hospital/icu/header/instruction/instruction-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/update-patient-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-right-buttons/header-right-buttons.tsx
components/hospital/icu/main/tx-table/tx-table-container.tsx
components/hospital/icu/main/tx-table/tx-table-filter.tsx
components/hospital/icu/main/tx-table/tx-table.tsx
components/hospital/icu/sidebar/desktop-icu-sidebar.tsx
components/hospital/icu/sidebar/mobile/mobile-icu-sidebar-sheet.tsx
components/hospital/sidebar/mobile-sidebar.tsx
components/hospital/sidebar/sidebar.tsx

design: tablet 대응 UI 리팩토링

---

components/ui/table.tsx

hotfix: data table hover효과 삭제

---

components/hospital/admin/drug/drugs-data-table/drug-columns.tsx
components/hospital/admin/drug/upsert-drug-form/add-drug-dialog.tsx
components/hospital/admin/drug/upsert-drug-form/drug-form-schema.ts
components/hospital/admin/drug/upsert-drug-form/drug-form.tsx
components/hospital/admin/icu-settings/default-orders/default-orders-table.tsx
components/hospital/admin/icu-settings/vital-ref-range/vital-ref-range-settings.tsx
components/hospital/icu/common-dialogs/preview/read-only-chart-table.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-rows.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/quick-order-insert-input.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-border-checkbox.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-form.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-schema.ts
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/orderer/orderer-select-step.tsx
components/hospital/icu/main/template/add/template-orders-table.tsx
components/hospital/icu/main/template/edit/edit-template-orders.tsx
components/hospital/order-table/order-form.tsx
components/hospital/order-table/order-table-row.tsx
lib/services/admin/drug/drug.ts
lib/services/admin/icu/default-orders.ts
lib/services/icu/chart/order-mutation.ts
lib/services/icu/template/template.ts
lib/supabase/database.types.ts
lib/utils/utils.ts
types/icu/chart.ts

- 오더 테두리 표시 선택 추가
- 약물 추가 기능
- vitals hotfix
어떤 변경 사항이 있나요?

feat: icu-order border 테두리 강조 기능 추가

---

app/globals.css
components/on-boarding/signup-form.tsx

인풋요소 커서가 사라지는 문제 시도 1 

---

components/hospital/icu/main/chart/selected-chart/chart-body/chart-memos/single-memo/single-memo.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-rows.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/delete-orders-alert-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-form.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/selected-order-action-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/template/add-template-order-dialog.tsx
lib/services/icu/chart/order-mutation.ts

- 오더 다중 선택 후 Command out 시 모달을 통한 액션
- 메모 grip 추가
어떤 변경 사항이 있나요?

refactor: 오더 다중 선택 액션 추가

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-row-title.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/quick-order-insert-input.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx
components/hospital/icu/main/tx-table/tx-table-filter.tsx

메모 그립, 오더 다중선택 액션 추가, 오더색 디자인 개편

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-row-cells.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/tx-detail-insert-step.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/tx-log.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-schema.ts
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-select-user-step.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-upsert-dialog.tsx
components/hospital/icu/main/tx-table/tx-table-cell.tsx
lib/store/icu/tx-mutation.ts

feat: tx_result optional

---

app/hospital/[hos_id]/icu/[target_date]/layout.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-memos/single-memo/single-memo.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-row-title.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-right-buttons/copy-chart-button.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-right-buttons/export-dialog/export-dialog-utils.tsx
lib/services/icu/get-icu-data.ts
lib/supabase/database.types.ts
providers/basic-hos-data-context-provider.tsx

오더 색 표시 방법 1. 보여주기

---

app/globals.css
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-row-cells.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-rows.tsx
components/hospital/icu/sidebar/filters/filters.tsx
components/hospital/icu/sidebar/filters/sort-filter.tsx
components/hospital/icu/sidebar/icu-sidebar.tsx
hooks/use-icu-sidebar-filter.tsx
types/icu/chart.ts

feat: 환자 목록 내 정렬 필터 추가

---

hooks/use-long-press.tsx

fix: 모바일 버전 longPress 복원

---

components/ui/table.tsx

feat: 가로선 hover부활

---

app/hospital/[hos_id]/icu/[target_date]/layout.tsx
components/hospital/admin/icu-settings/orderer/orderer-setting.tsx
components/hospital/admin/icu-settings/orderer/orderer-tab.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/chart-table-body.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-row-cells.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-rows.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/tx-detail-insert-step.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-select-user-step.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-upsert-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-right-buttons/export-dialog/export-dialog-utils.tsx
components/hospital/icu/main/tx-table/tx-table-cell.tsx
components/hospital/icu/main/tx-table/tx-table.tsx
constants/admin/admin-setting-items.ts
hooks/use-upsert-tx.tsx
lib/services/admin/icu/orderer.ts
lib/services/icu/get-icu-data.ts
lib/store/icu/icu-order.ts
lib/supabase/database.types.ts
providers/basic-hos-data-context-provider.tsx

- 관리자 - 처치자 표기 여부 토글 기능 추가
- tx insert custom hook 추가
어떤 변경 사항이 있나요?

feat: 처치자 표기 여부 기능 추가

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/tx-log.tsx

- `담당자` -> `처치자` 표기명 변경
- 간편 입력('$')시 로그 결과 가공
어떤 변경 사항이 있나요?

refactor: TX 로그 리팩토링

---

app/hospital/[hos_id]/layout.tsx
components/hospital/icu/header/icu-header.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/cpcr-et-tube/cpcr-et-tube.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/group/group-badge.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/group/group.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/in-and-out-date.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/in-date.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/out-date.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/out-due-date.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/rer-der/rer-der.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/chart-header.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-right-buttons/header-right-buttons.tsx
components/hospital/icu/sidebar/mobile/mobile-icu-sidebar.tsx
components/hospital/icu/sidebar/patient-list.tsx

design: 태블릿 반응형 UI 스타일링

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/tx-detail-insert-step.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-select-user-step.tsx
hooks/use-upsert-tx.tsx

hotfix: 차트 내 체중 입력 시 바이탈 업데이트

---

components/hospital/patients/patient-form.tsx

hotfix : 품종선택 메모이제이션

---

components/hospital/icu/main/chart/chart.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/orderer/orderer-select-step.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/chart-header.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/header-center.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/vital-chart/update-vital-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/vital-chart/vital-chart-content.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/vital-chart/vital-chart-date-tick.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/vital-chart/vital-chart-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/vital-chart/vital-chart-form-schema.ts
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/vital-chart/vital-chart-sidebar.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/vital-chart/vital-chart-tooltip.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/vital-chart/vital-chart.tsx
constants/hospital/icu/chart/vital.ts
hooks/use-upsert-tx.tsx
lib/services/icu/chart/vitals.ts
lib/supabase/database.types.ts
lib/utils/analysis.ts
types/icu/chart.ts

- 체중(`body_weight`)만 현재 활성화
- 막대 그래프 클릭 시 바이탈 수정(update) 모달 활성화
- 데이터 수정 후 UI 즉시 업데이트 구현중..
어떤 변경 사항이 있나요?

feat: 바이탈 변화 추이 확인할 수 있는 chart 기능

---

components/hospital/icu/main/chart/selected-chart/chart-header/header-center/vital-chart/vital-chart.tsx

fix: description 변경

---

components/hospital/patients/patient-form.tsx

hotfix: 배포버전에서 품종선택이안된다고 함

---

components/hospital/admin/drug/upsert-drug-form/drug-form.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/cpcr-et-tube/cpcr-et-tube-update-form.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-form.tsx
components/hospital/order-table/order-form.tsx
components/hospital/patients/patient-form.tsx
components/on-boarding/create-hospital/create-hospital-form.tsx

form.watch 사용부분 use no memo 선언

---

components/hospital/patients/birth-date-picker.tsx

Refactor: 환자 등록 과정 생년월일 선택 시 캘린더 유지

---

components/hospital/icu/header/date-picker/header-date-picker.tsx
components/hospital/icu/header/date-picker/header-date-selector.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-body.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-memos/chart-memos.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-memos/memo-color-picker.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-memos/memo-group.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-memos/single-memo/single-memo.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-memos/sort-memo-button.tsx
constants/hospital/icu/chart/colors.ts
lib/services/hospital-home/notice.ts
package.json
pnpm-lock.yaml
types/icu/chart.ts

- 공지사항 추가 시 최상단에 추가됨
- 메모 추가 시 위치 방식 선택(토글)
어떤 변경 사항이 있나요?

refactor: 공지사항 & 메모 추가 시 추가 위치 변경

---

components/hospital/icu/main/chart/chart.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-header/chart-table-header.tsx
components/hospital/icu/main/tx-table/tx-table-container.tsx
components/hospital/icu/main/tx-table/tx-table.tsx
components/hospital/icu/sidebar/desktop-icu-sidebar.tsx
components/hospital/icu/sidebar/filters/filters.tsx
components/hospital/icu/sidebar/filters/group-filter.tsx
components/hospital/icu/sidebar/filters/sort-filter.tsx
components/hospital/icu/sidebar/filters/vet-filter.tsx
components/hospital/icu/sidebar/register-dialog/register-dialog.tsx
constants/hospital/sidebar-items.tsx

1. 퇴원 환자 차트 세로 스크롤 활성화
2. 북마크 차트 미리보기에서 빈 table header 삭제
3. 입원 환자 필터 로직 버그 수정
4. 처치표 필터링 로직 버그 수정
어떤 변경 사항이 있나요?

refactor: UI 리팩토링 및 버그 수정

---

app/layout.tsx
app/manifest.ts
components/hospital/admin/icu-settings/orderer/orderer-setting.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/quick-order-insert-input.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-header/chart-table-header.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-form.tsx
components/hospital/icu/main/tx-table/tx-table.tsx
components/hospital/icu/sidebar/filters/group-filter.tsx
components/hospital/icu/sidebar/filters/sort-filter.tsx
components/hospital/icu/sidebar/filters/vet-filter.tsx
constants/admin/admin-setting-items.ts
constants/hospital/icu/chart/order.ts
constants/hospital/sidebar-items.tsx
lib/services/admin/diet/diet.ts
lib/services/admin/staff/drug-settings.ts
lib/services/icu/chart/get-diets.ts
lib/services/icu/chart/get-drugs.ts
lib/services/icu/chart/order-mutation.ts
lib/services/icu/chart/vitals.ts
next.config.mjs

manifest, 아이콘 캐싱

---

app/hospital/[hos_id]/icu/[target_date]/layout.tsx
components/hospital/icu/footer/icu-footer.tsx
components/hospital/icu/main/chart/add-chart-dialogs/add-chart-dialogs.tsx
components/hospital/icu/main/chart/add-chart-dialogs/add-default-chart-dialog.tsx
components/hospital/icu/main/chart/add-chart-dialogs/bookmark/add-bookmark-chart-dialog.tsx
components/hospital/icu/main/chart/add-chart-dialogs/copy-prev-chart-dialog.tsx
components/hospital/icu/main/chart/add-chart-dialogs/copy-prev-io-chart-dialog.tsx
components/hospital/icu/main/chart/add-chart-dialogs/paste-copied-chart-dialog.tsx
components/hospital/icu/main/chart/chart-entry.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/quick-order-insert-input.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/delete-order-alert-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/delete-orders-alert-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/orderer/orderer-select-step.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-select-user-step.tsx
components/hospital/icu/sidebar/date-selector/icu-date-picker.tsx
components/hospital/icu/sidebar/date-selector/icu-date-selector.tsx
hooks/use-icu-realtime.tsx
unused/realtime-sub-store/realtime-subscription.ts

구독여부 전역스토어 삭제, 리얼타임 구독 시간 더 짧게

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx

fix: `!isSorting` 조건문을 통해 깜빡임 현상 제거

---

components/hospital/icu/main/chart/add-chart-dialogs/add-chart-dialogs.tsx
components/hospital/icu/main/chart/add-chart-dialogs/template/add-template-order-dialog.tsx
components/hospital/icu/main/chart/add-chart-dialogs/template/paste-template-button.tsx
components/hospital/icu/main/chart/add-chart-dialogs/template/paste-template-columns.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/selected-order-action-dialog.tsx

refactor: Add chart 단계에서 북마크 제거 및 `템플릿 선택`으로 리팩토링

---

app/hospital/share/[icu_io_id]/page.tsx
components/hospital/icu/common-dialogs/preview/read-only-chart/read-only-chart-table.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/in-and-out-date.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/in-date.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/out-date.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/out-due-date.tsx
components/hospital/share/header/icu-share-date-picker.tsx
components/hospital/share/header/icu-share-patient-info.tsx
components/hospital/share/icu-share-chart-infos.tsx
components/ui/highlight-guide.tsx
components/ui/indicator.tsx
constants/hospital/share/index.ts

1. Props
```ts
// components/ui/highlight-guide.tsx
export default function HighlightGuide({
steps,
className,
}: HighlightGuideProps}
.
.
.
type HighlightGuideProps = {
steps: typeof GUIDE_STEPS  // 타겟 쿼리명, 가이드 타이틀, 가이드 설명 정보
className?: string         // 트리거 버튼 ClassName
}
```
2. GUIDE_STEPS 구조
```
{
target: string      // 하이라이트할 요소의 `data-helper` query 속성값
title: string       // 가이드 타이틀
description: string // 가이드 설명
}
```
3. 사용 예시 (하이라이트하고자 하는 컴포넌트에 'data-guide' 프로퍼티 선언)
```ts
<HighlightGuide 
steps={ICU_CHART_GUIDE_STEPS}
className="bottom-4 right-4"
/>
--- 
<div
className="..."
data-guide="date-picker"
>
<Button> ...
<div/>
```
어떤 변경 사항이 있나요?

feat: share 페이지 하이라이트-가이드 기능 추가

---

components/hospital/icu/main/chart/selected-chart/chart-body/chart-memos/memo-group.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-memos/single-memo/single-memo.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/vital-chart/vital-chart.tsx
constants/hospital/icu/chart/order.ts
constants/hospital/icu/chart/vital.ts
lib/services/icu/chart/vitals.ts
lib/utils/analysis.ts
types/icu/chart.ts

- 체크리스트 기본 항목 `혈당` 추가
- 첫, 마지막 메모 스타일링
- 차트 분석 리팩토링
어떤 변경 사항이 있나요?

feat: 체크리스트 기본 항목 `혈당` 추가

---

app/hospital/share/[icu_io_id]/page.tsx
components/common/auto-complete/auto-complete.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/cage/cage.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/chart-infos.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/chief-complaint.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/diagnosis.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/urgency/urgency.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-select-user-step.tsx
components/hospital/icu/sidebar/desktop-icu-sidebar.tsx
components/hospital/icu/sidebar/filters/vet-filter.tsx
components/hospital/icu/sidebar/mobile/mobile-icu-sidebar-sheet.tsx
components/hospital/icu/sidebar/mobile/mobile-icu-sidebar.tsx
components/hospital/icu/sidebar/patient-list.tsx
components/hospital/share/header/icu-share-date-picker.tsx
components/hospital/share/header/icu-share-header.tsx
components/hospital/share/header/icu-share-patient-info.tsx
components/hospital/share/icu-share-chart-infos.tsx
components/ui/highlight-guide.tsx
components/ui/select.tsx
constants/hospital/sidebar-items.tsx
hooks/use-upsert-tx.tsx
lib/services/icu/chart/add-icu-chart.ts
lib/services/icu/chart/update-icu-chart-infos.ts
lib/supabase/database.types.ts
lib/utils/utils.ts
types/icu/chart.ts

1. 공유(icu-share)페이지 로고(Vetool) 추가
2. 응급도 (`urgency`) column 추가
3. 응급도순 정렬 기능 추가
4. 자동완성 내 HelperToolTip 조건부 렌더링
5. 다중 처치 입력 시 toast 다중 렌딩 수정
6. 입원한 환자 수 계산 리팩토링
어떤 변경 사항이 있나요?

refactor: 개선사항 반영

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/images/tx-image-field.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/tx-detail-insert-step.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/tx-select-user-step.tsx
hooks/use-upsert-tx.tsx
lib/services/icu/chart/tx-mutation.ts

feat: 다중 TX 입력 시에도 파일 업로드

---

components/hospital/icu/main/chart/selected-chart/chart-header/header-right-buttons/export-dialog/export-buttons.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-right-buttons/export-dialog/export-pdf-button.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-right-buttons/export-dialog/export-png-button.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-right-buttons/export-dialog/export-text-button.tsx

feat: 차트 텍스트로 복사 기능 추가

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-rows.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/orderer-select-step.tsx
constants/hospital/register/breed.ts
lib/store/icu/icu-order.ts

feat: 오더 붙여넣기시 테두리 정보 포함, 품종 임시 추가

---

app/hospital/share/[icu_io_id]/page.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-header/chart-table-header.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/vital-chart/vital-chart-dialog.tsx
components/hospital/share/header/icu-share-header.tsx
components/ui/highlight-guide.tsx

공유 차트 바이탈 차트 추가

---

components/hospital/icu/main/chart/paste-chart-dialogs/template/paste-template-order-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/chart-infos.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-creator.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-header/order-width-button.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/vital-chart/vital-chart.tsx

입원정보 그리드 배열 변경, 모바일 일부 기능 제한

---

components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/chart-infos.tsx
components/ui/highlight-guide.tsx
lib/services/image/r2Client.ts

chore: 환경변수 private설정

---

app/api/image/route.ts
lib/services/image/r2Client.ts

fix: tx-image 에러 로그 활성화

---

lib/services/icu/chart/tx-mutation.ts

refactor: post url 백틱 제거

---

app/api/image/route.ts

refactor: runtime 'edge' 설정하여 서버리스 함수로 실행되도록 변경

---

hooks/use-upsert-tx.tsx
lib/services/icu/chart/tx-mutation.ts

refactor: URL Check

---

app/api/image/route.ts
hooks/use-upsert-tx.tsx

refactor: CORS header 설정

---

app/hospital/[hos_id]/icu/[target_date]/layout.tsx
components/hospital/home/header/hospital-home-header.tsx
components/hospital/home/header/patches-carousel.tsx
components/hospital/icu/footer/icu-footer.tsx
components/hospital/icu/footer/realtime-status.tsx
components/ui/data-table.tsx

feat: 벳툴 패치 공지사항 icu 하단에도 추가

---

app/api/image/route.ts
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/tx-detail-insert-step.tsx

WIP: route api 수정중

---

app/api/image/route.ts
lib/services/icu/chart/tx-mutation.ts
vercel.json

feat: Vercel headers 설정 추가

---

app/api/image/route.ts
hooks/use-upsert-tx.tsx
lib/services/icu/chart/tx-mutation.ts
lib/services/icu/chart/upload-images.ts

refactor: 이미지 업로드는 클라이언트에서 직접 API 라우트를 호출

---

components/hospital/icu/main/chart/paste-chart-dialogs/paste-chart-dialogs.tsx
components/hospital/icu/main/chart/paste-chart-dialogs/template/paste-template-order-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-header/chart-table-header.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-header/order-width-button.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx
components/hospital/icu/sidebar/patient-button.tsx

feat: 환자 목록 내 응급도 표기, 차트 내보내기 수정

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/images/view/tx-image-view-carousel.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/images/view/tx-image.tsx

style: tx-image 스타일링 수정

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/images/tx-image-field.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/images/view/tx-image-view-carousel.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/images/view/tx-image-view-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/images/view/tx-image-view-skeleton.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/images/view/tx-image.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/tx-detail-insert-step.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-right-buttons/export-dialog/export-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-right-buttons/export-dialog/export-text-button.tsx
next.config.mjs

- Layout Shift 방지
- 가로 스크롤 바 추가
- 차트 텍스트로 내보내기 시 Fluid 표기
어떤 변경 사항이 있나요?

refactor: TX 이미지 리팩토링 및 차트 텍스트로 내보내기 수정

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-form-field.tsx

refactor: 오더타입 변경 할 수 있는 기능 부활

---

app/api/image/route.ts

refactor: ExperimentalWarning 수정

---

app/api/image/route.ts
next.config.mjs

hotfix: tx-image ExperimentalWarning 에러

---

app/api/image/route.ts
next.config.mjs

hotfix: rollback image logic

---

app/api/image/route.ts

fix: 타임아웃 설정

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/images/upload/tx-image-upload-preview.tsx

fix: 동일 이미지에 대한 고유한 키 생성

---

app/api/image/route.ts
hooks/use-upsert-tx.tsx
lib/services/icu/chart/tx-mutation.ts
lib/services/icu/chart/upload-images.ts

fix: tx payload 413 error 수정

---

app/api/image/route.ts
hooks/use-upsert-tx.tsx
lib/services/icu/chart/upload-images.ts
lib/services/image/presigned-url.ts

- Vercel Serverless Function의 payload size 제한 (4MB)으로 인한 대용량 이미지 업로드 실패
- 모바일 환경에서 1MB 이상 이미지 업로드 시 업로드 실패
- 서버 리소스 부하 감소
```ts
// 1. 클라이언트에서 서버로 파일 전송
formData.append('files', file)
await fetch('/api/image', {
method: 'POST',
body: formData
})
// 2. 서버에서 (API ROUTE) 파일 처리 및 R2 업로드
export async function POST(req: NextRequest) {
const formData = await req.formData()
const files = formData.getAll('files')
await R2Client.putObject({
Bucket: process.env.R2_BUCKET_NAME,
Key: fileName,
Body: buffer,
```
```ts
1. 서버에서는 `Presigned URL`만 생성
// lib/services/image/presigned-url.ts
'use server'
export const getPresignedUrls = async (fileInfos, route, id, startIndex) => {
return fileInfos.map(async (fileInfo) => {
const command = new PutObjectCommand({
Bucket: process.env.R2_BUCKET_NAME,
Key: …
```

refactor: 이미지 업로드 시스템 개선 (Presigned URL 방식)

---

components/hospital/calculator/rer-mer/diet/diet-form.tsx
lib/calculators/fluid-rate.ts

refactor: species 계산값 수정

---

components/hospital/calculator/calculator-sidebar.tsx

style: border-radius 제거

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/tx-detail-insert-step.tsx
hooks/use-abnormal-vital.tsx
lib/utils/analysis.ts

1. 호흡수 `sr` 파싱
2. 혈압 `#`, 수축/이완, panting 파싱
어떤 변경 사항이 있나요?

refactor: 바이탈 오더 결과 파싱

---

components/hospital/calculator/selected-calculators.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-memos/chart-memos.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-memos/memo-group.tsx
constants/hospital/icu/calculator/calculator.ts
lib/services/icu/chart/update-icu-chart-infos.ts
types/icu/chart.ts

feat: 메모 그룹(a, b, c)간 drag & drop 기능 추가

---

app/hospital/[hos_id]/icu/[target_date]/layout.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-body.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/chart-infos.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/in-date.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/out-date.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/in-and-out-date/out-due-date.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-memos/chart-memos.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-header/chart-table-header.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx
components/ui/pinch-zoom-container.tsx

feat: chart-body mobile zoom and pinch

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-header/order-width-button.tsx
components/ui/pinch-zoom-container.tsx

refactor: mobile chart pinch zoom

---

app/hospital/[hos_id]/icu/[target_date]/layout.tsx
components/hospital/admin/icu-settings/default-orders/default-orders-table.tsx
components/hospital/common/default-template-order/dt-table-header.tsx
components/hospital/common/patient/patient-detail-info.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-body.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-header/chart-table-header.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-header/order-width-button.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/tx-detail-insert-step.tsx
components/hospital/icu/main/template/template-order-table.tsx
constants/hospital/icu/chart/order.ts
hooks/use-long-press.tsx
types/hospital/order.ts

refactor: 모바일 차트 뷰 리팩토링

---

components/hospital/icu/main/chart/selected-chart/chart-header/header-center/vital-chart/vital-chart-content.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/vital-chart/vital-chart-dialog.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-center/vital-chart/vital-chart.tsx
constants/hospital/icu/chart/vital.ts

feat: SPO2 바이탈 차트 추가

---

components/hospital/calculator/cri/drugs/dobutamine-cri.tsx
components/hospital/calculator/cri/drugs/furosemide-cri.tsx
components/hospital/icu/main/tx-table/tx-table-cell.tsx

refactor: 계산기 라벨 수정, 모바일 처치표에서 입원차트이동자동포커싱 기능

---

components/hospital/admin/icu-settings/icu-settings-tab.tsx

chore: 선호약물설정 일단 비활성화

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-creator-row.tsx

hotfix: 주사 타입 오더 인풋 임시 비활성화

---

components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/urgency/urgency.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-creator-row.tsx

feat: 응급도 `없음` select-value 추가

---

components/hospital/admin/icu-settings/hos-drug/hos-drug-setting.tsx

chore: 기본약물 row length 10개로

---

app/(company)/test/io/page.tsx
app/hospital/[hos_id]/page.tsx
app/hospital/share/[icu_io_id]/page.tsx
components/hospital/calculator/rer-mer/diet/diet-form.tsx
components/hospital/calculator/rer-mer/rer-mer-calculator.tsx
components/hospital/calculator/result/calculator-result.tsx
components/hospital/calculator/result/insert-order-button.tsx
components/hospital/calculator/selected-calculators.tsx
components/hospital/home/body/hospital-home-body.tsx
components/hospital/home/body/notice/notice.tsx
components/hospital/home/body/todo/todo.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-infos/vets/vets-update-form.tsx
components/hospital/icu/main/chart/selected-chart/chart-header/header-right-buttons/export-dialog/export-dialog-utils.tsx
components/ui/resizable.tsx
package.json
pnpm-lock.yaml

계산기 계산결과가 form에서 바로 반영이 안되는 에러 해결, 홈에 resizable ui 적용

---

components/hospital/icu/main/summary/table/summary-table.tsx
components/hospital/icu/main/tx-table/tx-table-header.tsx

feat: 처치표와 종합현황에서도 시간이 적용되게

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-form.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/order/order-time-settings.tsx

refactor: 오더다이얼로그에서 오더시간 설정 부분도 기본 시간과 동이하게

---

app/hospital/[hos_id]/icu/[target_date]/tx-table/page.tsx
components/common/no-result-squirrel.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/tx-detail-insert-step.tsx
components/hospital/icu/main/tx-table/time-tx-text-copy.tsx
components/hospital/icu/main/tx-table/tx-table-cell.tsx
components/hospital/icu/main/tx-table/tx-table-container.tsx
components/hospital/icu/main/tx-table/tx-table-header.tsx
components/hospital/icu/main/tx-table/tx-table-order-type-filter.tsx
components/hospital/icu/main/tx-table/tx-table.tsx
lib/schemas/icu/chart/tx-schema.ts
lib/services/icu/tx-table/fetch-icu-tx-table-data.ts
lib/utils/tx-table.ts

refactor: 처치표 리팩토링

---

components/hospital/admin/icu-settings/order-color-settings/color-display-method/color-display-method.tsx
components/hospital/admin/icu-settings/order-color-settings/color-picker/order-color-picker.tsx
components/hospital/admin/icu-settings/order-color-settings/color-picker/order-color-pickers.tsx
components/hospital/admin/icu-settings/order-color-settings/order-color-settings.tsx
components/hospital/icu/footer/icu-footer.tsx
components/hospital/icu/main/chart/chart.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-body.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/cell.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-creator/user-key-guide-message.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-body/order-row-cells.tsx
components/hospital/icu/main/chart/selected-chart/out-patient-cover.tsx

1. 오더타입 색상 설정에서 모든 칸 붉게 되는 문제 해결
2. 우클릭선택된 상태에서 좌클릭 비활성화, 좌클릭 선택된 상태에서 우클릭 비활성화
3. 퇴원한 환자 커버가 아래부분까지 커버하지 못하는 문제 해결
4. 입원차트 풋터에서 현재 경로에 따라 활성화 표시 안되었던 부분 수정

Overall refactoring

---

components/hospital/icu/main/chart/chart.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/chart-body.tsx

fix: 시간줄 고정안되는 문제 해결

---

components/hospital/icu/main/chart/selected-chart/chart-body/chart-memos/memo-group.tsx
components/hospital/icu/main/chart/selected-chart/chart-body/table/chart-table-header/current-time-indicator.tsx
components/hospital/icu/main/summary/table/summary-table.tsx
components/hospital/icu/main/tx-table/tx-table-header.tsx

time indicator to tx table and summary table also

---

components/hospital/calculator/calculator-sidebar.tsx
components/hospital/calculator/kcl/kcl-table.tsx
components/hospital/calculator/kcl/kcl.tsx
components/hospital/calculator/selected-calculators.tsx
constants/hospital/icu/calculator/calculator.ts
constants/hospital/kcl.ts

Introduces a new KCl supplement calculator, including UI components and constants for KCl dosage and fluid rates. Updates the calculator sidebar and selected calculators to support KCl calculation, and adds KCL supplement table data for reference.
어떤 변경 사항이 있나요?

Add KCl supplement calculator

---

components/hospital/home/body/notice/notice.tsx
components/hospital/home/body/notice/upsert-notice-dialog.tsx
components/hospital/home/body/todo/single-todo.tsx
components/hospital/home/body/todo/todo-date-picker.tsx
components/hospital/home/body/todo/todo-filter.tsx
components/hospital/home/body/todo/todo-list.tsx
components/hospital/home/body/todo/todo-skeleton.tsx
components/hospital/home/body/todo/todo.tsx
components/hospital/home/body/todo/upsert-todo-dialog.tsx
hooks/use-todo.tsx
lib/schemas/hospital-home/hospital-home-schemas.ts
lib/services/hospital-home/todo.ts
lib/utils/utils.ts

Todo date error

---

lib/utils/utils.ts

fix: 자정에 투두 시간 오류나는 부분

---

components/hospital/icu/main/chart/selected-chart/chart-body/table/tx/detail-insert-step/tx-detail-insert-step.tsx

이미지 기능 비활성화

---

components/hospital/calculator/calculator-sidebar.tsx
components/hospital/home/body/todo/todo-filter.tsx
lib/utils/utils.ts

New refactoring
